name: Deployment

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: .cargo/target

      - run: cargo test --manifest-path ./lib/btree/Cargo.toml

      - uses: jetli/wasm-pack-action@v0.3.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16.10.0
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - run: |
          echo ted.a1liu.com >> .dist/CNAME
          touch .dist/.nojekyll

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree .dist add --all
      - run: git commit -m "Automatic Deploy action run by github-actions"
      - run: git push origin HEAD:gh-pages --force
