name: Deployment

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .cargo/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo test
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build:website
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree .dist add --all
      - run: git commit -m "Automatic Deploy action run by github-actions"
      - run: git push origin HEAD:gh-pages --force
